apiVersion: apps/v1
kind: Deployment
metadata:
  name: rose-game-ai-reference
  labels:
    app: rose-game-ai-reference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rose-game-ai-reference
  template:
    metadata:
      labels:
        app: rose-game-ai-reference
    spec:
      containers:
      - name: rose-game-ai-reference
        image: quay.io/rose/rose-game-ai-reference:latest  # Modify with your Docker image name and tag.
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: rose-game-ai-reference
spec:
  selector:
    app: rose-game-ai-reference
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer  # Exposes the Service externally using a cloud provider's load balancer.
